### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by dashedstripes** [dashedstripes/zendesk-node-api#2]
Hey @Garethderioth I think the travis tests are failing after the PR because of the following files which in the master branch are called config.example.js and .env.example:

<img width="322" alt="screen shot 2016-08-20 at 13 52 11" src="https://cloud.githubusercontent.com/assets/4217557/17831326/88db12b2-66dd-11e6-8e9a-6b8bfc52b7bc.png">
<img width="424" alt="screen shot 2016-08-20 at 13 52 08" src="https://cloud.githubusercontent.com/assets/4217557/17831327/89f5b97c-66dd-11e6-9157-43fe42efd4eb.png">

It seems that this line may be to blame:

<img width="460" alt="screen shot 2016-08-20 at 13 53 13" src="https://cloud.githubusercontent.com/assets/4217557/17831333/b1cf971a-66dd-11e6-96d5-4f7f9a56fc1f.png">

Would you recommend checking for enviroment variable as well as dotenv as a fallback measure?

**Comment by Garethderioth** [comment]
@dashedstripes Since the `dotenv.load()` is in a try catch should not be a problem with Travis. I think that the problem it is related to the load of the `config.js` file. Probably the better way is to load the config variables from the environment too.

You can pass it encrypted environment variables to travis.yml file: https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

I did something related:
https://github.com/Garethderioth/unlisted-friends/blob/master/.travis.yml
https://github.com/Garethderioth/unlisted-friends/blob/master/tests/helpers/env-constants.js

**Comment by dashedstripes** [comment]
thanks @Garethderioth I've updated the travis config and some of the config, it's now passing :)

**Comment by Garethderioth** [comment]
Awesome!
